grant usage on schema public to service_role;

create table if not exists public.deal_temperature_snapshots (
  id bigint generated by default as identity primary key,
  source text not null,
  captured_at timestamptz not null,
  model_version smallint not null default 2,
  sample_count integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source, captured_at)
);

alter table public.deal_temperature_snapshots enable row level security;
revoke all on table public.deal_temperature_snapshots from public, anon, authenticated;
grant select, insert, update, delete on table public.deal_temperature_snapshots to service_role;
revoke all on sequence public.deal_temperature_snapshots_id_seq from public, anon, authenticated;
grant usage, select on sequence public.deal_temperature_snapshots_id_seq to service_role;

create index if not exists idx_deal_temperature_snapshots_source_time
  on public.deal_temperature_snapshots (source, captured_at desc);

create index if not exists idx_deal_temperature_snapshots_captured_at
  on public.deal_temperature_snapshots (captured_at desc);

comment on table public.deal_temperature_snapshots is
  '30-minute aggregate samples used to tune the cross-source temperature model';
