create table if not exists public.deal_temperature_snapshots (
  id bigint generated by default as identity primary key,
  source text not null,
  captured_at timestamptz not null,
  model_version smallint not null default 2,
  sample_count integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source, captured_at)
);

create index if not exists idx_deal_temperature_snapshots_source_time
  on public.deal_temperature_snapshots (source, captured_at desc);

create index if not exists idx_deal_temperature_snapshots_captured_at
  on public.deal_temperature_snapshots (captured_at desc);

alter table public.deal_temperature_snapshots enable row level security;

comment on table public.deal_temperature_snapshots is
  '30-minute aggregate samples used to tune the cross-source temperature model';
